### PR TITLE
Fix login error + minor fixes

### PR DESCRIPTION
**Pull request by niko247**

### CODE REVIEW

**Comment by erlandasz** [comment]
doesn't show distance on PersonCard, looking into why this could be happening rn

**Comment by rcasiell92** [comment]
Hey,

Is tind3r working for you? I keep getting the login error. Tried adding your file to chrome and still same issue.

**Comment by niko247** [comment]
This must be first deployed to tind3r.com so you can run it normally, if you don't want to wait and want to test it on your local machine you need to import .zip extension from pull request and run your server locally, and change nonStoreId to the extension id that was generated after you added it to chrome (each time it's different) then run server and open localhost:3000

**Comment by rcasiell92** [comment]
Can you just walk me through the last bit? would love to test it on my machine.

1) i downloaded the zip extension
2) was able to add it to chrome

How do i change the extension ID and run server?

Appreciate the help

**Comment by rcasiell92** [comment]
I see the extension ID, so I guess i just need help figuring out how to

1) run server locally
2) change nonstoreid

**Comment by niko247** [comment]
You edit file:
In src/const/index.js you paste nonStoreId as your extension id from chrome
and like in readme you have to have node and yarn installed and then run in command line where is root of project:
yarn install
yarn start

**Comment by niko247** [comment]
> doesn't show distance on PersonCard, looking into why this could be happening rn

@erlandasz Fixed

**Comment by rcasiell92** [comment]
Hi Niko,

Rafael said he will no longer be updating the project. I'm a bit of a noob when it comes to this stuff, and have been using tind3r for awhile.

If I sent you some money ($25?) would you take the time to skype me and walk me through how to set this up on my own?

**Comment by SirNav** [comment]
not working for me, localhost:3000 opens up blank screen after starting local server

**Comment by rlesniak** [comment]
Thank you for your contribution!

**Pull request merged**
